from app import db

class Token(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    accessToken = db.Column(db.String(64), index=True, unique=True)
    used = db.Column(db.Boolean)

    def __repr__(self):
        return '<Token {}>'.format(self.accessToken)

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.String(255))
    category = db.Column(db.String(40))
    frontend = db.Column(db.String(40))
    ans01 = db.Column(db.String(255))
    ans02 = db.Column(db.String(255))
    ans03 = db.Column(db.String(255))
    ans04 = db.Column(db.String(255))
    ans05 = db.Column(db.String(255))
    ans06 = db.Column(db.String(255))
    ans07 = db.Column(db.String(255))
    ans08 = db.Column(db.String(255))
    ans09 = db.Column(db.String(255))
    ans10 = db.Column(db.String(255))
    ans11 = db.Column(db.String(255))
    ans12 = db.Column(db.String(255))
    ans13 = db.Column(db.String(255))
    ans14 = db.Column(db.String(255))
    ans15 = db.Column(db.String(255))
    ans16 = db.Column(db.String(255))
    ans17 = db.Column(db.String(255))
    ans18 = db.Column(db.String(255))
    ans19 = db.Column(db.String(255))
    ans20 = db.Column(db.String(255))
    sort = db.Column(db.Integer)

    def __repr__(self):
        return '<Question: {}>'.format(self.question)

class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    usedToken = db.Column(db.Integer, db.ForeignKey(Token.id))
    q01 = db.Column(db.String(40))
    q02 = db.Column(db.String(40))
    q03 = db.Column(db.String(40))
    q04 = db.Column(db.String(40))
    q05 = db.Column(db.String(40))
    q06 = db.Column(db.String(40))
    q07 = db.Column(db.String(40))
    q08 = db.Column(db.String(40))
    q09 = db.Column(db.String(40))
    q10 = db.Column(db.String(40))
    q11 = db.Column(db.String(40))
    q12 = db.Column(db.String(40))
    q13 = db.Column(db.String(40))
    q14 = db.Column(db.String(40))
    q15 = db.Column(db.String(40))
    q16 = db.Column(db.String(40))
    q17 = db.Column(db.String(40))
    q18 = db.Column(db.String(40))
    q19 = db.Column(db.String(40))
    q20 = db.Column(db.String(40))
    q21 = db.Column(db.String(40))
    q22 = db.Column(db.String(40))
    q23 = db.Column(db.String(40))
    q24 = db.Column(db.String(40))
    q25 = db.Column(db.String(40))
    q26 = db.Column(db.String(40))
    q27 = db.Column(db.String(40))
    q28 = db.Column(db.String(40))
    q29 = db.Column(db.String(40))
    q30 = db.Column(db.String(40))
    q31 = db.Column(db.String(40))
    q32 = db.Column(db.String(40))
    q33 = db.Column(db.String(40))

    def __repr__(self):
        return '<Answers given by token: {}>'.format(self.usedToken)
