"""added columns to Question

Revision ID: 360a835d676d
Revises: 
Create Date: 2018-03-13 16:41:46.617695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360a835d676d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accessToken', sa.String(length=64), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_accessToken'), 'token', ['accessToken'], unique=True)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usedToken', sa.Integer(), nullable=True),
    sa.Column('q01', sa.String(length=40), nullable=True),
    sa.Column('q02', sa.String(length=40), nullable=True),
    sa.Column('q03', sa.String(length=40), nullable=True),
    sa.Column('q04', sa.String(length=40), nullable=True),
    sa.Column('q05', sa.String(length=40), nullable=True),
    sa.Column('q06', sa.String(length=40), nullable=True),
    sa.Column('q07', sa.String(length=40), nullable=True),
    sa.Column('q08', sa.String(length=40), nullable=True),
    sa.Column('q09', sa.String(length=40), nullable=True),
    sa.Column('q10', sa.String(length=40), nullable=True),
    sa.Column('q11', sa.String(length=40), nullable=True),
    sa.Column('q12', sa.String(length=40), nullable=True),
    sa.Column('q13', sa.String(length=40), nullable=True),
    sa.Column('q14', sa.String(length=40), nullable=True),
    sa.Column('q15', sa.String(length=40), nullable=True),
    sa.Column('q16', sa.String(length=40), nullable=True),
    sa.Column('q17', sa.String(length=40), nullable=True),
    sa.Column('q18', sa.String(length=40), nullable=True),
    sa.Column('q19', sa.String(length=40), nullable=True),
    sa.Column('q20', sa.String(length=40), nullable=True),
    sa.Column('q21', sa.String(length=40), nullable=True),
    sa.Column('q22', sa.String(length=40), nullable=True),
    sa.Column('q23', sa.String(length=40), nullable=True),
    sa.Column('q24', sa.String(length=40), nullable=True),
    sa.Column('q25', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['usedToken'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_index(op.f('ix_token_accessToken'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
