"""added room for more questions

Revision ID: e91dc1571af9
Revises: ea03e5765552
Create Date: 2018-04-05 15:40:16.873243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91dc1571af9'
down_revision = 'ea03e5765552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('q34', sa.String(length=40), nullable=True))
    op.add_column('answer', sa.Column('q35', sa.String(length=40), nullable=True))
    op.add_column('answer', sa.Column('q36', sa.String(length=40), nullable=True))
    op.add_column('answer', sa.Column('q37', sa.String(length=40), nullable=True))
    op.add_column('answer', sa.Column('q38', sa.String(length=40), nullable=True))
    op.add_column('answer', sa.Column('q39', sa.String(length=40), nullable=True))
    op.add_column('answer', sa.Column('q40', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'q40')
    op.drop_column('answer', 'q39')
    op.drop_column('answer', 'q38')
    op.drop_column('answer', 'q37')
    op.drop_column('answer', 'q36')
    op.drop_column('answer', 'q35')
    op.drop_column('answer', 'q34')
    # ### end Alembic commands ###
