"""empty message

Revision ID: ea03e5765552
Revises: cb21865d9401
Create Date: 2018-04-03 14:04:18.452367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea03e5765552'
down_revision = 'cb21865d9401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('password', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_token_password'), 'token', ['password'], unique=True)
    op.drop_index('ix_token_accessToken', table_name='token')
    op.drop_column('token', 'accessToken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('accessToken', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_token_accessToken', 'token', ['accessToken'], unique=True)
    op.drop_index(op.f('ix_token_password'), table_name='token')
    op.drop_column('token', 'password')
    # ### end Alembic commands ###
